### ISSUE TITLE
Waving flag too extreme

### ISSUE THREAD

**Issue by Raspfarbend** [LucasBerbesson/teatime#1]
Waving should be +/- 5 degrees from **servo_max_angle**

but in the code for flag_right **servo_min_angle** is used.
so the waving flag runs wild (bouncing between 90° and 30°).

```
int flag_left = servo_max_angle + 5; 
int flag_right = servo_min_angle - 5;
```

https://github.com/LucasBerbesson/teatime/blob/cecfcf678b8149b35f6ea7d9c6981882d992b76b/cupoftea.ino#L17

**Comment by LucasBerbesson** [comment]
that's right, thanks

**Comment by Raspfarbend** [comment]
fixed and deployed in under one hour - awesome
